//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonVisuals.Properties {
    using System.CodeDom.Compiler;
    using System.Configuration;
    using System.Diagnostics;
    using System.Drawing;
    using System.Runtime.CompilerServices;

    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Consolas, 12pt")]
        public Font StreamDeckDefaultFont {
            get {
                return ((Font)(this["StreamDeckDefaultFont"]));
            }

            set {
                this["StreamDeckDefaultFont"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color StreamDeckDefaultFontColor {
            get {
                return ((Color)(this["StreamDeckDefaultFontColor"]));
            }

            set {
                this["StreamDeckDefaultFontColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("White")]
        public Color StreamDeckDefaultBackgroundColor {
            get {
                return ((Color)(this["StreamDeckDefaultBackgroundColor"]));
            }

            set {
                this["StreamDeckDefaultBackgroundColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int ButtonFaceOffsetX {
            get {
                return ((int)(this["ButtonFaceOffsetX"]));
            }

            set {
                this["ButtonFaceOffsetX"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int ButtonFaceOffsetY {
            get {
                return ((int)(this["ButtonFaceOffsetY"]));
            }

            set {
                this["ButtonFaceOffsetY"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string LastImageFileDialogLocation {
            get {
                return ((string)(this["LastImageFileDialogLocation"]));
            }

            set {
                this["LastImageFileDialogLocation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int OffsetX {
            get {
                return ((int)(this["OffsetX"]));
            }

            set {
                this["OffsetX"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("22")]
        public int OffsetY {
            get {
                return ((int)(this["OffsetY"]));
            }

            set {
                this["OffsetY"] = value;
            }
        }
    }
}
