using DCS_BIOS.misc;
using NonVisuals.Radios;
using Xunit;

namespace NonVisuals.Tests.Radios 
{
    public class RadioPanelPZ69Mi8Tests
    {

        [Theory]
        [InlineData(0, 0, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(0, 1, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(0, 2, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(0, 3, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(0, 4, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(0, 5, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(0, 6, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(0, 7, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(0, 8, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(0, 9, DCSBIOSCommand.DCSBIOS_INCREMENT)]

        [InlineData(1, 0, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(1, 1, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(1, 2, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(1, 3, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(1, 4, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(1, 5, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(1, 6, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(1, 7, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(1, 8, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(1, 9, DCSBIOSCommand.DCSBIOS_INCREMENT)]

        [InlineData(2, 0, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(2, 1, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(2, 2, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(2, 3, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(2, 4, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(2, 5, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(2, 6, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(2, 7, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(2, 8, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(2, 9, DCSBIOSCommand.DCSBIOS_INCREMENT)]

        [InlineData(3, 0, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(3, 1, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(3, 2, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(3, 3, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(3, 4, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(3, 5, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(3, 6, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(3, 7, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(3, 8, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(3, 9, DCSBIOSCommand.DCSBIOS_INCREMENT)]

        [InlineData(4, 0, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(4, 1, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(4, 2, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(4, 3, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(4, 4, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(4, 5, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(4, 6, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(4, 7, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(4, 8, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(4, 9, DCSBIOSCommand.DCSBIOS_DECREMENT)]

        [InlineData(5, 0, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(5, 1, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(5, 2, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(5, 3, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(5, 4, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(5, 5, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(5, 6, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(5, 7, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(5, 8, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(5, 9, DCSBIOSCommand.DCSBIOS_DECREMENT)]

        [InlineData(6, 0, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(6, 1, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(6, 2, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(6, 3, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(6, 4, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(6, 5, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(6, 6, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(6, 7, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(6, 8, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(6, 9, DCSBIOSCommand.DCSBIOS_DECREMENT)]

        [InlineData(7, 0, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(7, 1, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(7, 2, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(7, 3, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(7, 4, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(7, 5, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(7, 6, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(7, 7, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(7, 8, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(7, 9, DCSBIOSCommand.DCSBIOS_DECREMENT)]

        [InlineData(8, 0, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(8, 1, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(8, 2, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(8, 3, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(8, 4, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(8, 5, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(8, 6, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(8, 7, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(8, 8, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(8, 9, DCSBIOSCommand.DCSBIOS_DECREMENT)]

        [InlineData(9, 0, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(9, 1, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(9, 2, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(9, 3, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(9, 4, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(9, 5, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(9, 6, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(9, 7, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(9, 8, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(9, 9, DCSBIOSCommand.DCSBIOS_DECREMENT)]

        public void GetCommandDirectionFor0To9Dials_ShouldReturn_ExpectedValues(int desiredDialPosition, uint actualDialPosition, string expectedValue)
        {
            Assert.Equal(expectedValue, RadioPanelPZ69Mi8.GetCommandDirectionFor0To9Dials(desiredDialPosition, actualDialPosition));
        }

        [Theory]
        [InlineData(10, 10, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 11, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 12, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 13, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 14, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 15, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 21, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 22, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 23, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(10, 38, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(10, 39, DCSBIOSCommand.DCSBIOS_INCREMENT)]

        [InlineData(11, 10, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(11, 11, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(11, 12, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(11, 13, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(11, 14, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(11, 15, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(11, 21, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(11, 22, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(11, 23, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(11, 38, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(11, 39, DCSBIOSCommand.DCSBIOS_INCREMENT)]

        [InlineData(12, 10, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(12, 11, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(12, 12, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(12, 13, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(12, 14, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(12, 15, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(12, 21, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(12, 22, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(12, 23, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(12, 38, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(12, 39, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        
        [InlineData(13, 10, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(13, 11, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(13, 12, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(13, 13, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(13, 14, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(13, 15, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(13, 21, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(13, 22, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(13, 23, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(13, 38, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(13, 39, DCSBIOSCommand.DCSBIOS_INCREMENT)]

        [InlineData(14, 10, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(14, 11, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(14, 12, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(14, 13, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(14, 14, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(14, 15, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(14, 21, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(14, 22, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(14, 23, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(14, 38, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(14, 39, DCSBIOSCommand.DCSBIOS_INCREMENT)]

        //infinite loop [InlineData(15, 10, RadioPanelPZ69Base.Increase)]
        //infinite loop [InlineData(21, 10, RadioPanelPZ69Base.Increase)]
        //infinite loop [InlineData(22, 10, RadioPanelPZ69Base.Increase)]
        //infinite loop [InlineData(23, 10, RadioPanelPZ69Base.Increase)]
        //infinite loop [InlineData(24, 10, RadioPanelPZ69Base.Increase)]
        //infinite loop [InlineData(25, 10, RadioPanelPZ69Base.Increase)]

        [InlineData(37, 10, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 11, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 12, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 13, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 14, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 15, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 21, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 22, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 23, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 27, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(37, 28, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(37, 29, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(37, 30, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(37, 37, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 38, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(37, 39, DCSBIOSCommand.DCSBIOS_DECREMENT)]

        [InlineData(38, 10, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 11, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 12, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 13, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 14, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 15, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 21, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 22, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 23, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 27, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(38, 28, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(38, 29, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(38, 30, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(38, 37, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(38, 38, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(38, 39, DCSBIOSCommand.DCSBIOS_DECREMENT)]

        [InlineData(39, 10, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 11, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 12, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 13, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 14, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 15, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 21, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 22, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 23, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 27, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        [InlineData(39, 28, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(39, 29, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(39, 30, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(39, 37, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(39, 38, DCSBIOSCommand.DCSBIOS_INCREMENT)]
        [InlineData(39, 39, DCSBIOSCommand.DCSBIOS_DECREMENT)]
        public void GetCommandDirectionForR863ManualDial1_ShouldReturn_ExpectedValues(int desiredDialPosition, uint actualDialPosition, string expectedValue)
        {
            Assert.Equal(expectedValue, RadioPanelPZ69Mi8.GetCommandDirectionForR863ManualDial1(desiredDialPosition, actualDialPosition));
        }
    }
}
